export const FETCH_ACTION = "FETCH_ACTION";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_FAILED = "FETCH_FAILED";
export const BOOKMARK_ADD_ITEM = "BOOKMARK_ADD_ITEM";
export const BOOKMARK_REMOVE_ITEM = "BOOKMARK_REMOVE_ITEM";
